/* 
**  mod_filter.c -- Apache sample filter module
**  [Autogenerated via ``apxs -n filter -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_filter.c
**
**  Then activate it in Apache's httpd2-prefork.conf file for instance
**  for the URL /filter in as follows:
**
**    #   httpd2-prefork.conf
**    LoadModule filter_module modules/mod_filter.so
**    <Location /filter>
**    SetHandler filter
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /filter and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/filter 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_filter.c
*/ 

#include <string.h>

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "http_log.h"
#include "http_request.h"
#include "ap_config.h"
#include "util_filter.h"
#include "apr_lib.h"
#include "apr_general.h"

/*  declearation of call-back  */
static const char s_szCaseFilterName[] = "CaseFilter";
typedef struct
{
    int nCaseEnabled;
} case_config_t;

static int
filter_handler(request_rec *r);

static void *
CaseFilterCreateServerConfig(apr_pool_t *p, server_rec *s);

static void
CaseFilterInsertFilter(request_rec *r);

static apr_status_t 
CaseFilterOutputFilter(ap_filter_t *f, apr_bucket_brigade *p);

static const char *
CaseFilterEnable(cmd_parms *cmd, void *dummy, int arg);

static void
filter_register_hooks(apr_pool_t *p);

static const command_rec CaseFilterCmds[] =
{
    AP_INIT_FLAG("CaseFilter", CaseFilterEnable, NULL, RSRC_CONF,
                 "Run a case filter on this host"),
    { NULL }
};

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA filter_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                            /* create per-dir    config structures */
    NULL,                            /* merge  per-dir    config structures */
    CaseFilterCreateServerConfig,    /* create per-server config structures */
    NULL,                            /* merge  per-server config structures */
    CaseFilterCmds,                  /* table of config file commands       */
    filter_register_hooks            /* register hooks                      */
};

/*  implement of call-back  */
static void *
CaseFilterCreateServerConfig(apr_pool_t *p, server_rec *s)
{
    case_config_t *conf = apr_pcalloc(p, sizeof *conf);
    conf->nCaseEnabled = 0;
    return conf;
}

static void
CaseFilterInsertFilter(request_rec *r)
{
    ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, r->server,
                      "Input Filter called");
    case_config_t *conf = ap_get_module_config(r->server->module_config, &filter_module);
    if(conf == 0 || conf->nCaseEnabled == 0)
    {
        ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, r->server,
                      "config was enabled");
        return;
    }
    ap_add_output_filter(s_szCaseFilterName, NULL, r, r->connection);
}

static apr_status_t
CaseFilterOutputFilter(ap_filter_t *f, apr_bucket_brigade *p)
{
    request_rec *r = f->r;
    conn_rec *c = r->connection;
    apr_bucket *pBucketIn;
    apr_bucket_brigade *pBucketBrigadeOut;
    pBucketBrigadeOut = apr_brigade_create(r->pool, c->bucket_alloc);

    ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, r->server,
                      "Output Filter called");
    for(pBucketIn = APR_BRIGADE_FIRST(p);
        pBucketIn != APR_BRIGADE_SENTINEL(p);
        pBucketIn = APR_BUCKET_NEXT(pBucketIn))
    {
        const char *data = NULL;
        apr_size_t len;
        char *buffer;
        apr_size_t n;
        apr_bucket *pBucketOut;

        if(APR_BUCKET_IS_EOS(pBucketIn))
        {
            apr_bucket *pBucketEOS = apr_bucket_eos_create(c->bucket_alloc);
            APR_BRIGADE_INSERT_TAIL(pBucketBrigadeOut, pBucketEOS);
            continue;
        }

        apr_bucket_read(pBucketIn, &data, &len, APR_BLOCK_READ);
        buffer = apr_bucket_alloc(len, c->bucket_alloc);
        for(n = 0; n < len; ++n)
        {
            buffer[n] = apr_toupper(data[n]);
        }

        pBucketOut = apr_bucket_heap_create(buffer, len, apr_bucket_free, c->bucket_alloc);
        APR_BRIGADE_INSERT_TAIL(pBucketBrigadeOut, pBucketOut);
    }

    apr_brigade_cleanup(p);
    return ap_pass_brigade(f->next, pBucketBrigadeOut);
}

static const char *
CaseFilterEnable(cmd_parms *cmd, void *dummy, int arg)
{
    const char *err = ap_check_cmd_context(cmd, GLOBAL_ONLY);
    if(err)
    {
        ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, cmd->server,
                     err);
        return err;
    }
    case_config_t *conf = ap_get_module_config(cmd->server->module_config, &filter_module);
    conf->nCaseEnabled = arg;
    return NULL;
}

static int
filter_handler(request_rec *r)
{
    if (strcmp(r->handler, "filter")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_filter.c\n", r);
    return OK;
}

static void
filter_register_hooks(apr_pool_t *p)
{

//    ap_hook_handler(filter_handler, NULL, NULL, APR_HOOK_MIDDLE);
    ap_hook_insert_filter(CaseFilterInsertFilter, NULL, NULL, APR_HOOK_MIDDLE);
    ap_register_output_filter(s_szCaseFilterName, CaseFilterOutputFilter, NULL, AP_FTYPE_RESOURCE);
    ap_hook_handler(filter_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

