/* 
**  mod_demo.c -- Apache sample demo module
**  [Autogenerated via ``apxs -n demo -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_demo.c
**
**  Then activate it in Apache's httpd2-prefork.conf file for instance
**  for the URL /demo in as follows:
**
**    #   httpd2-prefork.conf
**    LoadModule demo_module modules/mod_demo.so
**    <Location /demo>
**    SetHandler demo
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /demo and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/demo 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_demo.c
*/ 

#include <string.h>
#include <stdlib.h>

#include "httpd.h"
#include "http_log.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

/* The sample content handler */
typedef struct 
{
    int convert_type;
} demo_config_t;

static void *
create_config(apr_pool_t *pool, server_rec *server);

static const char *
set_mod_config(cmd_parms *params, void *config, const char *arg);

static void
demo_register_hooks(apr_pool_t *p);

static const command_rec demo_cmds[] = 
{
    AP_INIT_TAKE1("ConvertType",
                  set_mod_config,
                  NULL,
                  RSRC_CONF,
                  "convert type of post data"),

    {0}
};

module AP_MODULE_DECLARE_DATA demo_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    create_config,         /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    demo_cmds,             /* table of config file commands       */
    demo_register_hooks    /* register hooks                      */
};

static void *
create_config(apr_pool_t *pool, server_rec *server)
{
    demo_config_t *conf = (demo_config_t *)apr_palloc(pool, sizeof(*conf));
    conf->convert_type = 0;
    return conf;
}

static const char *
set_mod_config(cmd_parms * params, void *config, const char *arg)
{
    demo_config_t *conf = NULL;
    const char *err = ap_check_cmd_context(params, GLOBAL_ONLY);
    if(err)
    {
        ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, params->server,
                     err);
        return err;
    }

    conf = (demo_config_t *)ap_get_module_config(params->server->module_config, &demo_module);

    char *pConvertType = ap_getword_conf(params->pool, &arg);
    if(pConvertType && strcasecmp(pConvertType, "1") == 0)
    {
        ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, params->server,
                     "convert type = 1;");
        conf->convert_type = 1;
    }
    else if(pConvertType && strcasecmp(pConvertType, "0") == 0)
    {
        ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, params->server,
                     "convert type = 0;");
        conf->convert_type = 0;
    }
    else
    {
        ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, params->server,
                     "unkown convert type;");
        return "unknown convert type";
    }
    return NULL;
}

static int
read_post_data(request_rec * r, char **post, size_t * post_size)
{
    char buffer[1024] = {0};
    size_t bytes = 0, count = 0, offset = 0;

    if(ap_setup_client_block(r, REQUEST_CHUNKED_DECHUNK) != OK)
    {
        return HTTP_BAD_REQUEST;
    }

    if(ap_should_client_block(r))
    {
        for(bytes = ap_get_client_block(r, buffer, 1024);
            bytes > 0;
            bytes = ap_get_client_block(r, buffer, 1024))
        {
            count += bytes;
            if(count > *post_size)
            {
                *post = (char*)realloc(*post, count);
                if(*post == NULL)
                {
                    return HTTP_INTERNAL_SERVER_ERROR;
                }
            }

            *post_size = count;
            offset = count - bytes;
            memcpy((char*)*post + offset, buffer, bytes);
        }
    }
    else
    {
        *post_size = 0;
        return OK;
    }

    return OK;
}

static int
demo_handler(request_rec *r)
{
    ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, r->server,
                     "enter demo handler");
    if (strcmp(r->handler, "demo")) {
        return DECLINED;
    }

    if (r->method_number != M_GET && r->method_number != M_POST)
    {
        return HTTP_METHOD_NOT_ALLOWED;
    }

    size_t post_size = 1024;
    char* post = (char*)malloc(post_size);
    if(post == NULL)
    {
        return HTTP_INTERNAL_SERVER_ERROR;
    }
    memset(post, 0, post_size);
    ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, r->server,
                     "before read post data");
    int ret = read_post_data(r, &post, &post_size);
    if(ret != OK)
    {
        free(post);
        post = NULL;
        post_size = 0;
        return ret;
    }

    ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, r->server,
                     "after read post data");
    ap_set_content_type(r, "text/html;charset=utf-8");
    ap_set_content_length(r, post_size);

    if(post_size == 0)
    {
        ap_rputs("no post data found\n", r);
        return OK;
    }

    ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, r->server,
                     "before get config");
    demo_config_t *conf = (demo_config_t *)ap_get_module_config(r->server->module_config, &demo_module);
    if(conf->convert_type == 1)
    {
        ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, r->server,
                     "convert type = 1 in handler");
        ap_rputs("convert type is 1\n", r);
        return OK;
    }

    ap_log_error(APLOG_MARK, APLOG_CRIT, APR_SUCCESS, r->server,
                 "after read config");
    ap_rputs(post, r);
    free(post);
    post = NULL;
    post_size = 0;
    return OK;
}

static void
demo_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(demo_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

